#!/bin/bash
# --------------------------------------------------------------------------------------------------
# caretakerd       Startup script for the stes caretaker Server
#
# chkconfig: - 70 15
# description: caretaker is a process that enables/disables sites
#
# processname: caretaked
# config:      /etc/caretakerd.conf
# pidfile:     /var/run/caretakerd.pid
# --------------------------------------------------------------------------------------------------
# Source function library.
. /etc/rc.d/init.d/functions

# This will prevent initlog from swallowing up a pass-phrase prompt if
# mod_ssl needs a pass-phrase from the user.
INITLOG_ARGS=""

# Path to the running script, server binary, and short-form for messages.
caretakerd=/usr/local/IntelROCCS/SitesCaretaker/caretakerd
prog=caretakerd
pidfile=${PIDFILE-/var/run/caretakerd.pid}
lockfile=${LOCKFILE-/var/lock/subsys/caretakerd}

RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

# Start caretaker daemon (caretakerd)
start() {
    echo -n $"Starting $prog:"
    daemon --user=cmsprod --pidfile=${pidfile} $caretakerd \&
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch ${lockfile}

    # this seems like a hack, but I do not know how to do it differently
    pid=`ps auxw | grep "/bin/bash $caretakerd" |tr -s ' '|cut -d' ' -f2`
    echo $pid > $pidfile

    return $RETVAL
}

# Stop caretaker daemon (caretakerd)
stop() {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile} -d ${STOP_TIMEOUT} $caretakerd
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p ${pidfile} $caretakerd
    RETVAL=$?
    ;;
  restart)
    stop
    start
    ;;
  condrestart|try-restart)
    if status -p ${pidfile} $caretakerd >&/dev/null
    then
      stop
      start
    fi
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status|help}"
    RETVAL=2
esac

exit $RETVAL
