#!/bin/bash
# --------------------------------------------------------------------------------------------------
# undertakerd       Startup script for the stes undertaker Server
#
# chkconfig: - 70 15
# description: undertaker is a process that enables/disables sites
#
# processname: undertaked
# config:      /etc/undertakerd.conf
# pidfile:     /var/run/undertakerd.pid
# --------------------------------------------------------------------------------------------------
# Source function library.
. /etc/rc.d/init.d/functions

# This will prevent initlog from swallowing up a pass-phrase prompt if
# mod_ssl needs a pass-phrase from the user.
INITLOG_ARGS=""

# Path to the running script, server binary, and short-form for messages.
undertakerd=/usr/local/IntelROCCS/SitesUndertaker/undertakerd
prog=undertakerd
pidfile=${PIDFILE-/var/run/undertakerd.pid}
lockfile=${LOCKFILE-/var/lock/subsys/undertakerd}

RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

# Start undertaker daemon (undertakerd)
start() {
    echo -n $"Starting $prog:"
    daemon --user=cmsprod --pidfile=${pidfile} $undertakerd \&
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch ${lockfile}

    # this seems like a hack, but I do not know how to do it differently
    pid=`ps auxw | grep "/bin/bash $undertakerd" |tr -s ' '|cut -d' ' -f2`
    echo $pid > $pidfile

    return $RETVAL
}

# Stop undertaker daemon (undertakerd)
stop() {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile} -d ${STOP_TIMEOUT} $undertakerd
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p ${pidfile} $undertakerd
    RETVAL=$?
    ;;
  restart)
    stop
    start
    ;;
  condrestart|try-restart)
    if status -p ${pidfile} $undertakerd >&/dev/null
    then
      stop
      start
    fi
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status|help}"
    RETVAL=2
esac

exit $RETVAL
