#!/bin/bash
# --------------------------------------------------------------------------------------------------
# Process to keep data dealer alive and well.
#
# v1.1                                                                   B.Barrefors (Aug 11, 2014)
# --------------------------------------------------------------------------------------------------
# set up variables

# always run on the same tim
today=$(date -d "now" +%Y/%m/%d)
runTime=$(date -d "$today 03:00" +%s)
currentTime=$(date -d "now" +%s)
timeToWait=$(($runTime - $currentTime))
if [ $timeToWait -le 0 ]
then
    tomorrow=$(date -d "tomorrow" +%Y/%m/%d)
    runTime=$(date -d "$tomorrow 03:00" +%s)
    currentTime=$(date -d "now" +%s)
    timeToWait=$(($runTime- $currentTime))
fi

sleep $timeToWait

while [ 1 ]
do
    loopInterval=24
    numLogFiles=15
    # prepare to start on the same time every time based on loop interval
    secs=$(date +%s --date="now")
    runTime=$(date '+%s' --date="@$((secs + $loopInterval*60*60))")

    # generate specific log file
    tag=`date "+%Y%m%d"`
    oldTag=$(date '+%Y%m%d' --date="@$((secs - $numLogFiles*24*60*60))")
    logFile=/local/cmsprod/IntelROCCS/DataDealer/Logs/data_dealer-$tag.log
    oldLogFile=/local/cmsprod/IntelROCCS/DataDealer/Logs/data_dealer-$oldTag.log
    reportFile=/local/cmsprod/IntelROCCS/DataDealer/Reports/data_dealer-$tag.report
    touch $logFile
    rm $oldLogFile

    echo " "                                                           >> $logFile
    echo " data dealer started -- $tag (cycle wait ${loopInterval}h)"  >> $logFile
    echo " "                                                           >> $logFile
    echo "   --> "`date`                                               >> $logFile
    echo " "                                                           >> $logFile
    stdbuf -o0 -e0 /usr/local/IntelROCCS/DataDealer/dataDealer.py      >> $logFile 2>&1
    stdbuf -o0 -e0 /usr/local/IntelROCCS/DataDealer/systemData.py      >> $logFile 2>&1
    stdbuf -o0 -e0 /usr/local/IntelROCCS/DataDealer/datasetTrend.py    >> $logFile 2>&1

    # ensure that the log and report information is updated
    rsync -Cavz --delete /local/cmsprod/IntelROCCS/DataDealer /home/cmsprod/public_html/IntelROCCS >& /dev/null

    # change symlinks for todays report and log
    ln -s /home/cmsprod/public_html/IntelROCCS/DataDealer/Logs/data_dealer-$tag.log /home/cmsprod/public_html/IntelROCCS/DataDealer/Logs/data_dealer-latest.log
    ln -s /home/cmsprod/public_html/IntelROCCS/DataDealer/Reports/data_dealer-$tag.report /home/cmsprod/public_html/IntelROCCS/DataDealer/Reports/data_dealer-latest.report

    # calculate the time until next run should start
    currentTime=$(date -d "now" +%s)
    timeToWait=$(($runTime- $currentTime))
    sleep $timeToWait
done

exit 0;
