#!/bin/bash
# --------------------------------------------------------------------------------------------------
# Process to keep Undertaker alive and well.
#
# v1.0                                                                         C.Paus (Mar 09, 2014)
# --------------------------------------------------------------------------------------------------
# initialize environment variables
source /usr/local/IntelROCCS/Undertaker/setupUndertaker.sh

while [ 1 ]
do

  # make sure the log directory exists
  mkdir -p $UNDERTAKER_DB
  if [ -e "$UNDERTAKER_DB" ]
  then
    #echo " Undertaker log area exists. Let's start!"
    sleep 1
  else
    echo ""
    echo " Undertaker database area could not be found ($UNDERTAKER_DB). EXIT!"
    echo ""
    exit 1
  fi

  # generate specific log file
  tag=`date "+%s"`
  logFile=$UNDERTAKER_DB/undertaker-$tag.log
  touch $logFile
  echo ""                                                                    >> $logFile
  echo " = = = =  I N I T I A L  S H E L L   E N V I R O N M E N T  = = = =" >> $logFile
  echo ""                                                                    >> $logFile
  env  | grep -v ^UNDERTAKER                                                  >> $logFile
  echo ""                                                                    >> $logFile
  echo " = = =  I N I T I A L  C A R E T A K E R   E N V I R O N M E N T = " >> $logFile
  echo ""                                                                    >> $logFile
  env  | grep ^UNDERTAKER                                                     >> $logFile
  echo ""                                                                    >> $logFile
  echo "[ PYTHON PATH: $PYTHONPATH ]"                                        >> $logFile
  echo ""                                                                    >> $logFile

  # ten loops over the process with one logfile (keep it small)
  for index in `echo 0 1 2 3 4 5 6 7 8 9`
  do
    # period 3600 * nHours
    let wait=3600*$UNDERTAKER_CYCLE_HOURS

    echo " "                                                         >> $logFile
    echo " undertaker loop $index started -- $tag (cycle wait $wait sec)" >> $logFile
    echo " "                                                         >> $logFile
    echo "   --> "`date`                                             >> $logFile
    echo " "                                                         >> $logFile
    stdbuf -o0 -e0 $UNDERTAKER_BASE/undertaker.py                      >> $logFile 2>&1

    # insure that the log information is updated
    rsync -Cavz --delete /local/cmsprod/IntelROCCS/Undertaker \
                         /home/cmsprod/public_html/IntelROCCS >& /dev/null
    sleep $wait
  done

done

exit 0;
