#!/bin/bash
# --------------------------------------------------------------------------------------------------
# data_dealerd  Startup script for the detox Server
#
# chkconfig: - 70 15
# description: DataDealer is a process which decides if a CMS dataset needs to be replicated
#              It also selects an appropriate destination site
#
# processname: data_dealerd
# config:      /etc/data_dealerd.conf
# pidfile:     /var/run/data_dealerd.pid
# --------------------------------------------------------------------------------------------------
# Source function library.
. /etc/rc.d/init.d/functions

# This will prevent initlog from swallowing up a pass-phrase prompt if
# mod_ssl needs a pass-phrase from the user.
INITLOG_ARGS=""

# Path to the running script, server binary, and short-form for messages.
#detoxd=/usr/sbin/detoxd
data_dealerd=/usr/local/IntelROCCS/DataDealer/data_dealerd
prog=data_dealerd
pidfile=${PIDFILE-/var/run/data_dealerd.pid}
lockfile=${LOCKFILE-/var/lock/subsys/data_dealerd}

RETVAL=0
STOP_TIMEOUT=${STOP_TIMEOUT-10}

# Start data dealer daemon (data_dealerd)
start() {
    echo -n $"Starting $prog:"
    daemon --user=cmsprod --pidfile=${pidfile} $data_dealerd \&
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch ${lockfile}

    # this seems like a hack, but I do not know how to do it differently
    pid=`ps auxw | grep "/bin/bash $data_dealerd" |tr -s ' '|cut -d' ' -f2`
    echo $pid > $pidfile

    return $RETVAL
}

# Stop data dealer daemon (data_dealerd)
stop() {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile} -d ${STOP_TIMEOUT} $data_dealerd
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status -p ${pidfile} $data_dealerd
    RETVAL=$?
    ;;
  restart)
    stop
    start
    ;;
  condrestart|try-restart)
    if status -p ${pidfile} $data_dealerd >&/dev/null
    then
      stop
      start
    fi
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status|help}"
    RETVAL=2
esac

exit $RETVAL
